# Generated by Django 5.0.3 on 2024-04-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolfees',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
