# Generated by Django 5.0.3 on 2024-04-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_schoolfees_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head_picture',
            field=models.ImageField(null=True, upload_to='general pictures'),
        ),
        migrations.AddField(
            model_name='department',
            name='welcome_note',
            field=models.TextField(null=True),
        ),
    ]
