# Generated by Django 5.0.3 on 2024-04-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_department_head_picture_department_welcome_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100)),
                ('welcome_note', models.TextField(null=True)),
                ('head_picture', models.ImageField(null=True, upload_to='general pictures')),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='dean_picture',
            field=models.ImageField(null=True, upload_to='general pictures'),
        ),
        migrations.AddField(
            model_name='school',
            name='welcome_note',
            field=models.TextField(null=True),
        ),
    ]
