# Generated by Django 5.0.3 on 2024-04-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_unit_school_dean_picture_school_welcome_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='dean_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='head_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='head_picture',
            field=models.ImageField(blank=True, null=True, upload_to='general pictures'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='welcome_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
