# Generated by Django 5.0.3 on 2024-04-14 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Biodata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('othername', models.CharField(max_length=200)),
                ('marital_status', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('date_of_birth', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('place_of_birth', models.CharField(max_length=200)),
                ('home_town', models.CharField(max_length=200)),
                ('state_of_origin', models.CharField(max_length=200)),
                ('lga_of_origin', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('tel1', models.CharField(max_length=200)),
                ('tel2', models.CharField(max_length=200)),
                ('contact_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nok_fullname', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=200)),
                ('nok_tel', models.CharField(max_length=200)),
                ('nok_email', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OLevelResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
