# Generated by Django 5.0.3 on 2024-04-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0003_programme_courseapplied'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=300)),
            ],
        ),
    ]
